### PR TITLE
metrics using docker stats api endpoint

### PR DESCRIPTION
**Pull request by paulczar**
hacking away at stuff at monitorama

### CODE REVIEW

**Comment by mattyjones** [comment]
@paulczar 

Can you take a look at the Travis output please.

Thanks

**Comment by mattyjones** [comment]
@paulczar  Can you update the changelog so I can merge and build this

Thanks!

**Comment by oba11** [comment]
@paulczar i v a suggestion.
I was thinking maybe we could use `container names` instead of `container id`.
If metrics are being sent to graphite, could have trouble identifying the containers.
if its in an environment where friendly container names are used then more data history would be accessible for analytics.
Can even introduce a switch `-n` for anyone interested in `container names` instead of `container id`

Its a suggestion and can be discarded if irrelevant.

Thanks.

**Comment by paulczar** [comment]
good idea.   I'd totally forgotten about this PR ... :)

**Comment by oba11** [comment]
Thanks alot @paulczar

**Pull request closed without merging**
