### PR TITLE
add seconds_ago option

### PR DESCRIPTION
**Pull request by aksentyev**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks @aksentyev. Can you add an entry to the CHANGELOG under unreleased and we'll get this merged.

**Comment by aksentyev** [comment]
@eheydrick Done.

**Comment by hd-deman** [comment]
:shipit:

**Comment by eheydrick** [comment]
Released in 1.1.0.

**Pull request merged**
