### PR TITLE
Fix docker api support

### PR DESCRIPTION
**Pull request by d4n13lbc**
## Pull Request Checklist

**Is this in reference to an existing issue?**
issue: https://github.com/sensu-plugins/sensu-plugins-docker/issues/45

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Suport docker api from version v1.18 to latest (1.29)

This fix is based on the following docker api response for [State][Running]:

https://docs.docker.com/engine/api/v1.29
section: INSPECT A CONTAINER
Example response:
``` 
	"State": {
		"Error": "",
		"ExitCode": 9,
		"FinishedAt": "2015-01-06T15:47:32.080254511Z",
		"OOMKilled": false,
		"Dead": false,
		"Paused": false,
		"Pid": 0,
		"Restarting": false,
		"Running": true,
		"StartedAt": "2015-01-06T15:47:32.072697474Z",
		"Status": "running"
	},
```

### CODE REVIEW

**Comment by majormoses** [comment]
is this backwards compatible with previous versions of docker? If not then we can attempt this do a rescue with the olf logic in place to remain backwards compatible.

**Comment by d4n13lbc** [comment]
It looks like there are support for [State][Running] since 1.18 version (I checked the different api versions of the documentation https://docs.docker.com/engine/api/v1.18/ and others) . It looks like [State][Status] is supported since 1.21 version.

**Comment by majormoses** [comment]
OK lets either check the version and make the appropriate changes or try new method and rescue and then try the older version.

**Comment by d4n13lbc** [comment]
This fix should work for all documented versions. I don't see documentation for previous versions (<1.18) and not even [State][Status] existed before 1.21

**Comment by majormoses** [comment]
Sorry I misunderstood you initially, Can we please document in readme or as a comment in the check that this check supports docker versions `>= 1.18`?

**Comment by majormoses** [comment]
I am not sure we can have a test with multiple docker versions I would need to look into that. This would be a docker in docker scenario...Minimally I need a CHANGELOG entry and ideally something documented somewhere the minimum version of docker we support.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-docker/versions/1.3.0

**Pull request merged**
