### PR TITLE
Very simple TLS support

### PR DESCRIPTION
**Pull request by DavidNorman**
## Pull Request Checklist

**Is this in reference to an existing issue?**
Yes - #24
#### General
- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [x] Update README with any necessary configuration snippets
- [ ] Binstubs are created if needed
- [x] RuboCop passes
- [x] Existing tests pass 
#### New Plugins
- [ ] Tests
- [ ] Add the plugin to the README
- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)
#### Purpose

This adds a simple TLS certs support for when the user has separate cert/key files.

### CODE REVIEW

**Comment by cwjohnston** [comment]
Hi @DavidNorman, thanks for the pull request! I think implementing TLS support is a very good idea. I have a couple thoughts on your proposed changes:

First, I think it would be more user-friendly and consistent with other plugins if we were to use command line options instead of environment variables for enabling this behavior. 

Secondly, I think its important that we support specifying the TLS verification mode via a command line flag as well. If we merge the feature without it, I'm sure support for this will be requested soon after.

Will you please consider the above suggestions? Thanks!

**Comment by eheydrick** [comment]
@DavidNorman any thoughts on @cwjohnston's feedback? Would be nice to have TLS support.

**Comment by DavidNorman** [comment]
Hi.  I have moved on to another (completely different) project.  Feel free to cherry pick some of the ideas here, but I have no longer the time to contribute, sorry.

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-docker/pull/33#issuecomment-279967369

**Pull request closed without merging**
