### PR TITLE
Update metric-docker-stats.rb

### PR DESCRIPTION
**Pull request by tata2000**
Allowing to get full response from docker for /containers/json

### CODE REVIEW

**Comment by eheydrick** [comment]
I like this. What do you think about switching the connection setup to use https://github.com/sensu-plugins/sensu-plugins-docker/blob/master/lib/sensu-plugins-docker/client_helpers.rb so we have consistency with all the plugins?

**Comment by entropyfarms** [comment]
Any update on this?  I am hitting the same bug (dealing with larger than single chunk docker response) and would hate to have to re-implement when there is a fix waiting for merge.

**Comment by tata2000** [comment]
@eheydrick I think it is a good idea, but I don't have the installation of sensu and the dockers anymore, so any change I do I'll not be able to test.

I suggest merging this pull request to fix a bug - and then replacing the connection.
it should be a simple change in the docker_api function where that strange if will be replaced with the new client from helpers.

I just removed the duplicate code and extracted it to a separate function.

**Comment by eheydrick** [comment]
I tested this and it works for me. Can you drop an entry in the CHANGELOG and we'll get this merged.

**Comment by majormoses** [comment]
@eheydrick do you want to take this up or just close this out?

**Comment by eheydrick** [comment]
@majormoses lets close it out. 04d2282b233230393315a3ad219dfaa0b65f15fd addressed this issue.

**Pull request closed without merging**
